### ISSUE TITLE
Would it be possible to read `ruby-version` from `.ruby-version`?

### ISSUE THREAD

**Issue by smaboshe** [standardrb/standard-ruby-action#19]
Thanks for the work on this GitHub Action!

In the options, there is a `with:` parameter that can be used to set the Ruby version for this GitHub Action to use. Is it possible to have this read from the `.ruby-version` of the project if one exists?

https://github.com/standardrb/standard-ruby-action?tab=readme-ov-file#options

**Comment by searls** [comment]
If you can figure out how to make that happen I'd be happy to accept a PR
